### ISSUE TITLE
no such file or directory 

### ISSUE THREAD

**Issue by ghost** [axl72/Hercules#1]
buen proyecto.

No se encuentra la siguiente ruta o archivo
./archives/mymusic.json

Traceback (most recent call last):
  File "menu.py", line 33, in <module>
  File "menu.py", line 44, in MainWindow
  File "services\Database.py", line 13, in __init__
  File "tinydb\database.py", line 94, in __init__
  File "tinydb\storages.py", line 113, in __init__
  File "tinydb\storages.py", line 32, in touch
FileNotFoundError: [Errno 2] No such file or directory: './archives/mymusic.json'

**Comment by axl72** [comment]
Eso creo que se debe a un problema con los imports de python pero ahora puedes coger directamente el binario a través del instalador en la página de releases.
